import type { EnvRef, EnvVarDefinition } from "./types";

const ENV_KEY_PATTERN = /^[A-Z][A-Z0-9_]*$/;

export function envRef(name: string, defaultValue?: string, options: { prefix?: string; suffix?: string } = {}): EnvRef {
  return { kind: "env", name, defaultValue, ...options };
}

export function renderEnvRef(ref: EnvRef): string {
  assertEnvKey(ref.name);
  const prefix = ref.prefix ?? "";
  const suffix = ref.suffix ?? "";
  if (ref.defaultValue === undefined) {
    return `${prefix}\${${ref.name}}${suffix}`;
  }
  return `${prefix}\${${ref.name}:-${ref.defaultValue}}${suffix}`;
}

export function assertEnvKey(key: string): void {
  if (!ENV_KEY_PATTERN.test(key)) {
    throw new Error(`Invalid env key: ${key}`);
  }
}

export function validateEnvDefinitions(env: EnvVarDefinition[]): string[] {
  const errors: string[] = [];
  const seen = new Set<string>();

  for (const item of env) {
    if (!ENV_KEY_PATTERN.test(item.key)) {
      errors.push(`${item.key} must match ${ENV_KEY_PATTERN.source}`);
    }
    if (seen.has(item.key)) {
      errors.push(`${item.key} is defined more than once`);
    }
    seen.add(item.key);
  }

  return errors;
}

export function renderEnvExample(env: EnvVarDefinition[]): string {
  const lines = [
    "# Generated by Secure Docker Stack Builder.",
    "# Do not commit real secrets. Replace placeholder values locally.",
    ""
  ];

  for (const item of env) {
    assertEnvKey(item.key);
    lines.push(`# ${item.description}`);
    if (item.secret) {
      lines.push("# Secret: keep this value out of git, logs, tickets, and screenshots.");
    }
    if (item.escapeDollar) {
      lines.push("# Compose escaping: if the raw value contains $, write it as $$ in .env.");
    }
    const value = item.defaultValue ?? item.exampleValue ?? item.placeholder ?? "";
    lines.push(`${item.key}=${value}`);
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}
